<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB2_Control" Id="{f3ae371c-7e7d-41b3-b42c-11221479fa8f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB2_Control
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//loadingstation
Parts.Loadingstation(inputbelt := Parts.Belt.BoxReady, 
	weighbridge := Parts.Weighbridge.Output,
	q_crane => Parts.Crane.LoadReady);]]></ST>
    </Implementation>
    <LineIds Name="FB2_Control">
      <LineId Id="16" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="17" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>