<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Template" Id="{85c32724-8ce3-4d97-a01c-2989eae97e86}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Template
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Template">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>