<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB4_Devices" Id="{e2efe802-8b38-48d8-a591-337ee5822c42}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB4_Devices
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//devices are not implemented for this project]]></ST>
    </Implementation>
    <LineIds Name="FB4_Devices">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>