<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Motor_Notimplemented" Id="{7d4abe09-fc4f-42ac-9265-2a154e6bbf0e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Motor_Notimplemented
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Motor_Notimplemented">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>