<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Sensor_Notimplemented" Id="{bf58be98-0551-4cb2-83fe-ff7fd445bd23}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Sensor_Notimplemented
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Sensor_Notimplemented">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>